apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woocommerce-store.fullname" . }}-db-secret
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.wordpress.env.WORDPRESS_DB_PASSWORD | quote }}