apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "woocommerce-store.fullname" . }}-init
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure

      securityContext:
        fsGroup: 33

      initContainers:
        - name: wait-for-wordpress
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for WordPress deployment..."
              kubectl wait --for=condition=available --timeout=300s \
                deployment/{{ include "woocommerce-store.fullname" . }} \
                -n {{ .Release.Namespace }} || true

              echo "Waiting for WordPress pod..."
              kubectl wait --for=condition=ready --timeout=300s \
                pod -l app.kubernetes.io/instance={{ .Release.Name }} \
                -n {{ .Release.Namespace }} || true

              echo "â³ Waiting 60s for WordPress initialization..."
              sleep 60

      containers:
        - name: wp-cli-setup
          image: wordpress:cli

          securityContext:
            runAsUser: 33
            runAsGroup: 33

          command:
            - /bin/sh
            - -c
            - |
              set -e
              
              cd /var/www/html
              
              echo "Checking WordPress files..."
              
              # Wait for wp-config.php
              max_retries=12
              retry_count=0
              while [ ! -f wp-config.php ] && [ $retry_count -lt $max_retries ]; do
                echo "â³ Waiting for WordPress files... ($((retry_count+1))/$max_retries)"
                sleep 10
                retry_count=$((retry_count+1))
              done
              
              if [ ! -f wp-config.php ]; then
                echo "WordPress not initialized."
                exit 1
              fi
              
              echo "WordPress files found!"
              
              SITE_URL="http://{{ include "woocommerce-store.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
              
              echo "Installing with placeholder URL: $SITE_URL"
              
              if wp core is-installed --allow-root 2>/dev/null; then
                echo "WordPress already installed."
              else
                echo "ðŸš€ Installing WordPress..."
                wp core install \
                  --url="$SITE_URL" \
                  --title="{{ .Values.storeName }}" \
                  --admin_user={{ .Values.woocommerce.adminUser }} \
                  --admin_password={{ .Values.woocommerce.adminPassword }} \
                  --admin_email={{ .Values.woocommerce.adminEmail }} \
                  --skip-email \
                  --allow-root
                echo "WordPress installed!"
              fi
              
              # Install WooCommerce
              if wp plugin is-installed woocommerce --allow-root 2>/dev/null; then
                echo "WooCommerce already installed."
                wp plugin activate woocommerce --allow-root 2>/dev/null || true
              else
                echo "Installing WooCommerce..."
                wp plugin install woocommerce --activate --allow-root
                echo "WooCommerce installed!"
              fi
              
              # Set permalinks
              wp rewrite structure '/%postname%/' --allow-root
              wp rewrite flush --allow-root
              
              # Disable SSL
              wp option update woocommerce_force_ssl_checkout 'no' --allow-root 2>/dev/null || true
              
              # Skip WooCommerce wizard
              wp option update woocommerce_onboarding_profile '{"skipped":true}' --format=json --allow-root 2>/dev/null || true
              
              echo "Store setup complete!"
              echo "URLs will be updated by worker to NodePort"

          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.env.WORDPRESS_DB_HOST | quote }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.env.WORDPRESS_DB_NAME | quote }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.env.WORDPRESS_DB_USER | quote }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: WORDPRESS_TABLE_PREFIX
              value: {{ .Values.wordpress.env.WORDPRESS_TABLE_PREFIX | quote }}

          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html

      volumes:
        - name: wordpress-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "woocommerce-store.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}

      serviceAccountName: {{ include "woocommerce-store.fullname" . }}-sa